SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE `BOOK` (
    `ID` INT (11) NOT NULL AUTO_INCREMENT,
    `PUBLICATION_YEAR` INT (4) NOT NULL,
    `NAME` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE `AUTHOR`(
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NOME` VARCHAR (255) NOT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE `BOOK_AUTHOR` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `BOOK` INT NOT NULL,
    `AUTHOR` INT NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`BOOK`) REFERENCES `BOOK`(`ID`),
    FOREIGN KEY (`AUTHOR`) REFERENCES `AUTHOR`(`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE `PUBLISHER` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR (255) NOT NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE `BOOK_PUBLISHER` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `BOOK` INT NOT NULL,
    `PUBLISHER` INT NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`BOOK`) REFERENCES `BOOK`(`ID`),
    FOREIGN KEY (`PUBLISHER`) REFERENCES `PUBLISHER`(`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE `USUARIO` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR (255) NOT NULL,
    `ADDRESS` VARCHAR (255) NOT NULL,
    `CPF` VARCHAR (11) NOT NULL,
    `BIRTH_DATE` DATE,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE `COLLECTION` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `BOOK` INT NOT NULL,
    `TOTAL_QUANTITY` INT NOT NULL,
    `AVAILABLE_QUANTITY` INT NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`BOOK`) REFERENCES `BOOK`(`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

CREATE TABLE `LOAN` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `BOOK` INT NOT NULL,
    `QUANTITY` INT NOT NULL,
    `WITHDRAW_DATE` DATE NOT NULL,
    `RETURN_DATE` DATE NOT NULL,
    `STATUS` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`BOOK`) REFERENCES `BOOK`(`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;